config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get '/login_failure', to: 'sessions#login_failure'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
	resource :ticgames do
		post 'make_move'
	end
  
  #get '/login', to: 'players#show'
  #post '/login', to: 'players#show'
	resources :games
	resources :players 
	resources :ticgames

	root 'dashboard#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
	has_many :gamesplayer
	has_many :players, through: :gamesplayer
end

app/models/games_player.rb
class GamesPlayer < ApplicationRecord
	belongs_to :player
	belongs_to :game
end

app/models/player.rb
class Player < ApplicationRecord
	validates :name, presence: true
	has_many :gamesplayer
	has_many :games, through: :gamesplayer
end

app/models/ticgame.rb
class Ticgame < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	def index
	
	end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
	def new
		@game = Game.new
	end
	def show
		@game = Game.find(params[:id])
		@player = Player.find(session[:player_id])
	end
	
	def create

		state = game_state
		@game = Game.new(state: state)
		
		if @game.save
			redirect_to @game, notice: "Game added to database!"
		else 
			render :new
		end
	end
	
	
	private
		def game_state
			size = params[:game][:size].to_i
			state = "0" * (size * size)
		end
	
	
end

app/controllers/player_controller.rb
class PlayerController < ApplicationController
	def new
		@player = Player.new
	end
	def index
		@player = Player.all
	end
	def show

	end
		
	def create
	
		@player = Player.new(player_params)
		binding.pry
		if @player.save
			redirect_to @player, notice: "Player added to database!"
		else 
			render :new
		end
	end
	
	private
		def player_params
			params.require(:player).permit(:name)
		end
	

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
	def new
		@player = Player.new
	end
	def index
		@player = Player.all
	end
	def show
		@player = Player.find(params[:id])
	end
		
	def create
		@player = Player.new(player_params)
		@player.elo = 1200
		if @player.save
			redirect_to @player, notice: "Player added to database!"
		else 
			render :new
		end
	end
	
	
	private
		def player_params
			params.require(:player).permit(:name)
		end
	

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
	player = Player.find_by(name: params[:player_name])
	if player
		session[:player_id] = player.id
		redirect_to root_path, notice: "logged in"
	else
		flash.now[:alert] = "Something went wrong :("
		redirect_to login_failure_path 
	end
  end

  def destroy
		session[:player_id] = nil
		redirect_to root_url, notice: "looged out"
  end
  


end

app/controllers/ticgames_controller.rb
class TicgamesController < ApplicationController
include Math
@@player_char = '@'
	def index
		@game = Ticgame.all
	end
	def new
		
	end
	def create
		@game = Ticgame.new
		size = params[:size].to_i
		state = '0' * size * size
		@game.state = state
		if @game.save
			redirect_to action: "show", id: @game.id  
		else
			render :new
		end
	end
	def show
		@id = params[:id]
		@game = Ticgame.find(@id)
		@row_length = sqrt(@game.state.length())
	end
	def make_move
		if @@player_char == 'X'
			@@player_char = '@'
		else
			@@player_char = 'X'
		end
		@id = params[:id]
		index = params[:index].to_i
		@game = Ticgame.find(@id)
		if @game.state[index] == '0'
			@game.state[index] = @@player_char
		end
		
		 
		state_array = string_to_array(sqrt(@game.state.length()),@game.state)
		coordinates = find_coordinates(state_array, sqrt(@game.state.length()), index)
		game_end = check_win_condition(state_array, sqrt(@game.state.length()), coordinates)
		#binding.pry
		@game.save
		redirect_to action: "show", id: @game.id
	end
	def string_to_array(size, state)
		game_array = Array.new(size) {Array.new(size)}
		
		for first_index in 0..size-1
			for second_index in 0..size-1
				game_array[first_index][second_index] = state[(first_index*size)+second_index]
			end
		end
		game_array
	end
	def find_coordinates(state_array, size, index)
		move_coordinate_x = 0
		move_coordinate_y = 0
		for first_index in 0..size-1
			for second_index in 0..size-1
				if (first_index*size) + second_index == index
					move_coordinate_x = first_index
					move_coordinate_y = second_index
				end
			end
		end
		return [move_coordinate_x, move_coordinate_y]
	end
	
	def check_win_condition(state_array, size, coordinates)
		return false
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/player_helper.rb
module PlayerHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/ticgames_helper.rb
module TicgamesHelper
end

app/views/dashboard/index.html.erb
<h1> Hello! Wanna play game?</h1>

<p>New Game</p>
<%= link_to image_tag("tictac.png", width:80, height:80), "games/new" %>
<br>
<%= link_to 'Create new player!', 'players/new' %> <!-- Here this player/new seems like not the best solution. Fix please -->
<p><%= link_to 'Already have an account', 'sessions/new' %> </p>

<p><%= link_to 'New offline tic tac toe!', 'ticgames/new' %> </p>

app/views/games/new.html.erb
<h1>New game!</h1>
Enter size of board (1 - 10)
	<%= form_with model: @game, local: true do |form| %>
		<%= form.label :size, "Enter board size" %>
		<%= form.number_field :size, min: 1, max: 10, step: 1 %>
		<div class="actions">
			<%= form.submit "Create Game" %>
		</div>
	<% end %>

app/views/games/show.html.erb
<h1> Game view </h1>
<p> Player name: <%= @player.name %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TicTacToeGame</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/player/show.html.erb
<h1> CREATING NEW PLAYER </h1>

<%= form_with model: @player, local: true do |form| %>
	<p>
		<%= form.label :name %><br>
		<%= form.text_field :name %>
	</p>
	<div class="actions">
		<%= form.submit "Create player" %>
	</div>
<% end %>

app/views/players/new.html.erb
<h1> CREATING NEW PLAYER </h1>

<%= form_with model: @player, local: true do |form| %>
	<p>
		<%= form.label :name %><br>
		<%= form.text_field :name %>
	</p>
	<div class="actions">
		<%= form.submit "Create player" %>
	</div>
<% end %>

app/views/players/show.html.erb
<h1> Hello Player: <%= @player.name %> <br> </h1>
<p> Your elo: <%= @player.elo %> </p>
<%= link_to "Strona główna", root_path%>

app/views/session/new.html.erb
<h1>Log in</h1>

<%= form_with url: 'player/show/:id', local: true do |form| %>
  <div>
    <%= form.label :player_name %>
    <%= form.text_field :player_name %>
  </div>

  <div>
    <%= form.submit "Log in"%>
  </div>
<% end %>

app/views/ticgames/new.html.erb
<h1>Create new game!</h1>

<%= form_with model: @ticgame, url: ticgames_path do |form| %>
	<%= form.label "Board size:" %> 
	<%= form.number_field :size, step: 1, max: 10, min: 3 %>
	<%= form.submit "Create game!" %>
<% end %>

app/views/ticgames/show.html.erb
<h1> Let's begin </h1>
<h2> Game ID: <%= @game.id %> </h2>

<table>
<tr>
<% for i in 0..@game.state.length()-1 %>
<th><%= button_to @game.state[i], action: "make_move", id: @game.id, index: i %></th>
	<% if (i+1) % @row_length == 0 %>
</tr>
	<% end %>
<% end %>
</tr>
</table>